<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Microsoft.VisualStudio.DiagnosticsHub.BenchmarkDotNetDiagnosers" />
    <PackageReference Include="Prism.Events" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Prism.Events.Extensions\Prism.Events.Extensions.csproj" />
  </ItemGroup>

</Project>
