<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>High-performance synchronous and ValueTask-based asynchronous event types for Prism.Events.</Description>
    <PackageTags>prism;events;event aggregator;pubsubevent;async;performance</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Events" />
    <Compile Update="Properties\Resources.Designer.cs" DesignTime="True" AutoGen="True" DependentUpon="Resources.resx" />
    <EmbeddedResource Update="Properties\Resources.resx" Generator="ResXFileCodeGenerator" LastGenOutput="Resources.Designer.cs" />
  </ItemGroup>

</Project>
